package com.shakeup.setofthree.SetGame;

import android.support.annotation.NonNull;

import com.shakeup.setgamelibrary.SetGame;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * Created by Jayson on 3/2/2017.
 *
 * Handles all UI actions generated by the GameFragment class. The contract
 * between interactions is specified in GameContract.java
 */

public class GamePresenter implements GameContract.UserActionsListener {

    private SetGame mSetGame;
    private GameContract.View mGameView;

    /**
     * Public constructor used to set up the presenter. Requires a reference to the calling View.
     * @param gameView A reference to the calling View
     */
    public GamePresenter(
            @NonNull GameContract.View gameView) {
        mGameView = checkNotNull(gameView, "mainMenu cannot be null!");
    }

    /**
     * Create a new instance of a SET Game and pass the data back to the
     * game fragment to be displayed and interacted with
     */
    @Override
    public void initGame() {
        mSetGame = new SetGame();

        mGameView.displayGame(mSetGame.getSetHand());
    }

    @Override
    public void submitSet(int indexOne, int indexTwo, int indexThree) {

    }
}
